import Utils
import numpy as np
import inputdata
if __name__ == "__main__":
    """
    导入遍历的训练标签数据+最优的损耗情况
    """
    bianli1=Utils.load("bianlixunlianflag1.npy")
    bianli2=Utils.load("bianlixunlianflag2.npy")
    bianli3=Utils.load("bianlixunlianflag3.npy")
    bianli4=Utils.load("bianlixunlianflag4.npy")
    bianli5=Utils.load("bianlixunlianflag5.npy")
    bianli6=Utils.load("bianlixunlianflag6.npy")
    bianli7=Utils.load("bianlixunlianflag7.npy")
    bianli8=Utils.load("bianlixunlianflag8.npy")
    bianli9=Utils.load("bianlixunlianflag9.npy")
    bianli10=Utils.load("bianlixunlianflag10.npy")
    bianli11=Utils.load("bianlixunlianflag11.npy")
    bianli12=Utils.load("bianlixunlianflag12.npy")
    bianli13=Utils.load("bianlixunlianflag13.npy")
    bianli14=Utils.load("bianlixunlianflag14.npy")
    bianli15=Utils.load("bianlixunlianflag15.npy")
    bianli16=Utils.load("bianlixunlianflag16.npy")
    bianli17=Utils.load("bianlixunlianflag17.npy")
    bianli18=Utils.load("bianlixunlianflag18.npy")
    bianli19=Utils.load("bianlixunlianflag19.npy")
    bianli20=Utils.load("bianlixunlianflag20.npy")
    bianli21=Utils.load("bianlixunlianflag21.npy")
    bianli22=Utils.load("bianlixunlianflag22.npy")
    bianli23=Utils.load("bianlixunlianflag23.npy")
    bianli24=Utils.load("bianlixunlianflag24.npy")
    bianli25=Utils.load("bianlixunlianflag25.npy")
    bianli26=Utils.load("bianlixunlianflag26.npy")
    bianli27=Utils.load("bianlixunlianflag27.npy")
    bianli28=Utils.load("bianlixunlianflag28.npy")
    bianli29=Utils.load("bianlixunlianflag29.npy")
    bianli30=Utils.load("bianlixunlianflag30.npy")
    bianli31=Utils.load("bianlixunlianflag31.npy")
    bianli32=Utils.load("bianlixunlianflag32.npy")
    bianli33=Utils.load("bianlixunlianflag33.npy")
    bianli34=Utils.load("bianlixunlianflag34.npy")
    bianli35=Utils.load("bianlixunlianflag35.npy")
    bianli36=Utils.load("bianlixunlianflag36.npy")
    bianli37=Utils.load("bianlixunlianflag37.npy")
    bianli38=Utils.load("bianlixunlianflag38.npy")
    bianli39=Utils.load("bianlixunlianflag39.npy")
    bianli40=Utils.load("bianlixunlianflag40.npy")


    consume1=Utils.load("bianlixunlianxiaohao1.npy")
    consume2=Utils.load("bianlixunlianxiaohao2.npy")
    consume3=Utils.load("bianlixunlianxiaohao3.npy")
    consume4=Utils.load("bianlixunlianxiaohao4.npy")
    consume5=Utils.load("bianlixunlianxiaohao5.npy")
    consume6=Utils.load("bianlixunlianxiaohao6.npy")
    consume7=Utils.load("bianlixunlianxiaohao7.npy")
    consume8=Utils.load("bianlixunlianxiaohao8.npy")
    consume9=Utils.load("bianlixunlianxiaohao9.npy")
    consume10=Utils.load("bianlixunlianxiaohao10.npy")
    consume11=Utils.load("bianlixunlianxiaohao11.npy")
    consume12=Utils.load("bianlixunlianxiaohao12.npy")
    consume13=Utils.load("bianlixunlianxiaohao13.npy")
    consume14=Utils.load("bianlixunlianxiaohao14.npy")
    consume15=Utils.load("bianlixunlianxiaohao15.npy")
    consume16=Utils.load("bianlixunlianxiaohao16.npy")
    consume17=Utils.load("bianlixunlianxiaohao17.npy")
    consume18=Utils.load("bianlixunlianxiaohao18.npy")
    consume19=Utils.load("bianlixunlianxiaohao19.npy")
    consume20=Utils.load("bianlixunlianxiaohao20.npy")
    consume21=Utils.load("bianlixunlianxiaohao21.npy")
    consume22=Utils.load("bianlixunlianxiaohao22.npy")
    consume23=Utils.load("bianlixunlianxiaohao23.npy")
    consume24=Utils.load("bianlixunlianxiaohao24.npy")
    consume25=Utils.load("bianlixunlianxiaohao25.npy")
    consume26=Utils.load("bianlixunlianxiaohao26.npy")
    consume27=Utils.load("bianlixunlianxiaohao27.npy")
    consume28=Utils.load("bianlixunlianxiaohao28.npy")
    consume29=Utils.load("bianlixunlianxiaohao29.npy")
    consume30=Utils.load("bianlixunlianxiaohao30.npy")
    consume31=Utils.load("bianlixunlianxiaohao31.npy")
    consume32=Utils.load("bianlixunlianxiaohao32.npy")
    consume33=Utils.load("bianlixunlianxiaohao33.npy")
    consume34=Utils.load("bianlixunlianxiaohao34.npy")
    consume35=Utils.load("bianlixunlianxiaohao35.npy")
    consume36=Utils.load("bianlixunlianxiaohao36.npy")
    consume37=Utils.load("bianlixunlianxiaohao37.npy")
    consume38=Utils.load("bianlixunlianxiaohao38.npy")
    consume39=Utils.load("bianlixunlianxiaohao39.npy")
    consume40=Utils.load("bianlixunlianxiaohao40.npy")

    """
    合并遍历的训练的标签数据+损耗情况
    """
    train_table=np.append(bianli1,bianli2,axis=0)
    train_table=np.append(train_table,bianli3,axis=0)
    train_table=np.append(train_table,bianli4,axis=0)
    train_table=np.append(train_table,bianli5,axis=0)
    train_table=np.append(train_table,bianli6,axis=0)
    train_table=np.append(train_table,bianli7,axis=0)
    train_table=np.append(train_table,bianli8,axis=0)
    train_table=np.append(train_table,bianli9,axis=0)
    train_table=np.append(train_table,bianli10,axis=0)
    train_table=np.append(train_table,bianli11,axis=0)
    train_table=np.append(train_table,bianli12,axis=0)
    train_table=np.append(train_table,bianli13,axis=0)
    train_table=np.append(train_table,bianli14,axis=0)
    train_table=np.append(train_table,bianli15,axis=0)
    train_table=np.append(train_table,bianli16,axis=0)
    train_table=np.append(train_table,bianli17,axis=0)
    train_table=np.append(train_table,bianli18,axis=0)
    train_table=np.append(train_table,bianli19,axis=0)
    train_table=np.append(train_table,bianli20,axis=0)
    train_table = np.append(train_table, bianli21, axis=0)
    train_table = np.append(train_table, bianli22, axis=0)
    train_table=np.append(train_table,bianli23,axis=0)
    train_table=np.append(train_table,bianli24,axis=0)
    train_table=np.append(train_table,bianli25,axis=0)
    train_table=np.append(train_table,bianli26,axis=0)
    train_table=np.append(train_table,bianli27,axis=0)
    train_table=np.append(train_table,bianli28,axis=0)
    train_table=np.append(train_table,bianli29,axis=0)
    train_table=np.append(train_table,bianli30,axis=0)
    train_table = np.append(train_table, bianli31, axis=0)
    train_table = np.append(train_table, bianli32, axis=0)
    train_table=np.append(train_table,bianli33,axis=0)
    train_table=np.append(train_table,bianli34,axis=0)
    train_table=np.append(train_table,bianli35,axis=0)
    train_table=np.append(train_table,bianli36,axis=0)
    train_table=np.append(train_table,bianli37,axis=0)
    train_table=np.append(train_table,bianli38,axis=0)
    train_table=np.append(train_table,bianli39,axis=0)
    train_table=np.append(train_table,bianli40,axis=0)

    train_consume =np.append(consume1,consume2,axis=0)
    train_consume =np.append(train_consume,consume3,axis=0)
    train_consume =np.append(train_consume,consume4,axis=0)
    train_consume =np.append(train_consume,consume5,axis=0)
    train_consume =np.append(train_consume,consume6,axis=0)
    train_consume =np.append(train_consume,consume7,axis=0)
    train_consume =np.append(train_consume,consume8,axis=0)
    train_consume =np.append(train_consume,consume9,axis=0)
    train_consume =np.append(train_consume,consume10,axis=0)
    train_consume =np.append(train_consume,consume11,axis=0)
    train_consume =np.append(train_consume,consume12,axis=0)
    train_consume =np.append(train_consume,consume13,axis=0)
    train_consume =np.append(train_consume,consume14,axis=0)
    train_consume =np.append(train_consume,consume15,axis=0)
    train_consume =np.append(train_consume,consume16,axis=0)
    train_consume =np.append(train_consume,consume17,axis=0)
    train_consume =np.append(train_consume,consume18,axis=0)
    train_consume =np.append(train_consume,consume19,axis=0)
    train_consume =np.append(train_consume,consume20,axis=0)
    train_consume =np.append(train_consume,consume21,axis=0)
    train_consume =np.append(train_consume,consume22,axis=0)
    train_consume =np.append(train_consume,consume23,axis=0)
    train_consume =np.append(train_consume,consume24,axis=0)
    train_consume =np.append(train_consume,consume25,axis=0)
    train_consume =np.append(train_consume,consume26,axis=0)
    train_consume =np.append(train_consume,consume27,axis=0)
    train_consume =np.append(train_consume,consume28,axis=0)
    train_consume =np.append(train_consume,consume29,axis=0)
    train_consume =np.append(train_consume,consume30,axis=0)
    train_consume =np.append(train_consume,consume31,axis=0)
    train_consume =np.append(train_consume,consume32,axis=0)
    train_consume =np.append(train_consume,consume33,axis=0)
    train_consume =np.append(train_consume,consume34,axis=0)
    train_consume =np.append(train_consume,consume35,axis=0)
    train_consume =np.append(train_consume,consume36,axis=0)
    train_consume =np.append(train_consume,consume37,axis=0)
    train_consume =np.append(train_consume,consume38,axis=0)
    train_consume =np.append(train_consume,consume39,axis=0)
    train_consume =np.append(train_consume,consume40,axis=0)

    print(train_table.shape)
    print(train_consume.shape)
    # Utils.save("bianli_table.npy",train_table)
    # Utils.save("bianli_consume.npy",train_consume)

    """
    保存训练集合和测试集合
    """
    origin_data = inputdata.get_data()
    length=len(origin_data)
    split = int(length * 0.8)
    print(split,length)

    temp=[]
    for i in train_table:
        temp.append(i.flatten())
    train_table=np.array(temp)
    # print(train_table.shape)
    Utils.save("bianli_train_table.npy", train_table[0:split])
    Utils.save("bianli_train_consume.npy", train_consume[0:split])
    Utils.save("bianli_pre_table.npy", train_table[split:length])
    Utils.save("bianli_pre_consume.npy", train_consume[split:length])
